version: "3.8"
name: "otamarket-app"
services:
    server:
        build: ./backend
        container_name: ota_server_cont
        ports:
            - "8080:8080"
        env_file:
            - project.env
        depends_on:
            - database
            - flyway
        develop:
            watch:
                - action: sync
                  path: ./backend
                  target: /app
                  ignore:
                      - .backend/node_modules/
                - action: rebuild
                  path: ./backend/package.json

    frontend:
        build: ./frontend
        container_name: ota_frontend_cont
        ports:
            - "5173:5173"
        env_file:
            - project.env
        depends_on:
            - server
            - database
            - flyway
        develop:
            watch:
                - action: sync
                  path: ./frontend
                  target: /app_f
                  ignore:
                      - .frontend/node_modules/
                - action: rebuild
                  path: ./frontend/package.json

    database:
        container_name: ota_db_cont
        image: postgres:14.1
        restart: "no"
        env_file:
            - project.env

    flyway:
        image: flyway/flyway:9.11.0-alpine
        depends_on:
            - database
        volumes:
            - .:/flyway/sql
        command: -connectRetries=60 -baselineOnMigrate=true migrate
        env_file:
            - project.env
