version: "3.8"
name: "otamarket-app"
services:
    server:
        build: ./backend
        container_name: server_cont
        ports:
            - "8080:8080"

        develop:
            watch:
                - action: sync
                  path: ./backend
                  target: /app
                  ignore:
                      - .backend/node_modules/
                - action: rebuild
                  path: ./backend/package.json

    frontend:
        build: ./frontend
        container_name: frontend_cont
        ports:
            - "5173:5173"

        develop:
            watch:
                - action: sync
                  path: ./frontend
                  target: /app_f
                  ignore:
                      - .frontend/node_modules/
                - action: rebuild
                  path: ./frontend/package.json
